### ISSUE TITLE
[bug] some thread died, maybe res = None ?

### ISSUE THREAD

**Issue by m4ndingo** [epsylon/orb#3]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/Users/mandingo/Documents/python/others/orb/core/orb.py", line 31, in run
    out = "HTTP/1.0 %s\r\n" % res["code"]
TypeError: 'NoneType' object has no attribute '__getitem**'

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/Users/mandingo/Documents/python/others/orb/core/orb.py", line 31, in run
    out = "HTTP/1.0 %s\r\n" % res["code"]
TypeError: 'NoneType' object has no attribute '__getitem**'

**Comment by epsylon** [comment]
multithreading will be implemented soon so probably that will fix this bug.
thanks for report!
